import { Geist, Geist_Mono } from "next/font/google"; 
import "./globals.css"; 
import Navbar from "../components/Navbar"; 
import AuthProvider from "@/components/providers/AuthProvider";

const geistSans = Geist({ 
  variable: "--font-geist-sans", 
  subsets: ["latin"], 
}); 

const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono", 
  subsets: ["latin"], 
}); 

export const metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
}; 

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <AuthProvider> {/* 🔥 WAJIB */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
