"use client";

import { Geist, Geist_Mono } from "next/font/google";
import { useState, useEffect } from "react";
import "./globals.css";
import Navbar from "../components/Navbar";
import LoginModal from "@/components/LoginModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showLogin, setShowLogin] = useState(false);

  useEffect(() => {
    const openLoginHandler = () => setShowLogin(true);
    window.addEventListener("openLogin", openLoginHandler);

    return () => {
      window.removeEventListener("openLogin", openLoginHandler);
    };
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <Navbar />

        {children}

        {/* 🔥 LOGIN POPUP GLOBAL */}
        <LoginModal
          isOpen={showLogin}
          onClose={() => setShowLogin(false)}
        />

      </body>
    </html>
  );
}
